plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.gradle.userdev' version '7.1.25'
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
    maven { url = uri("https://neoforged.net") }
    mavenCentral()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        // Добавь эту строку обратно:
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        programArgument '--nogui'
    }
}

sourceSets {
    main {
        resources {
            srcDir 'src/main/resources'
        }
    }
}

dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    // Подключаем Create и другие моды из папки libs
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}

// Задача по копированию ресурсов (рецептов, текстур)
tasks.withType(ProcessResources).configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

// Чтобы IDEA видела изменения в ресурсах без полной пересборки
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
processResources.outputs.upToDateWhen { false }