modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "create_additional_energy_sourses"
version = "1.0.0"
displayName = "Create: Additional Energy Sources"

[[dependencies."create_additional_energy_sourses"]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."create_additional_energy_sourses"]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

# --- ЗАВИСИМОСТЬ ОТ CREATE ---
[[dependencies.create_additional_energy_sourses]]
modId = "create"
type = "required" # Мод НЕ запустится без Create
ordering = "NONE"
side = "BOTH"

# Стало (Точное совпадение с внутренним ID мода из папки):
[[dependencies.create_additional_energy_sourses]]
modId = "createdieselgenerators"
type = "required"
ordering = "NONE"
side = "BOTH"


[[ponder.plugins]]
modId="create_additional_energy_sourses"
pluginClass="com.ruby.mod.create_additional_energy_sourses.ModPonderPlugin"
